import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import navStyles from "../styles/navbar.module.css";

export default function ModifiedNavBar() {
  const handleClick = () => {
    document.body.classList.add("transparent-nav");
  };
  return (
    <>
      <Head>
        <title>bone hollow studio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/leaf.svg"
          className="invert(68%) sepia(9%) saturate(467%) hue-rotate(64deg) brightness(93%) contrast(89%)"
        ></link>
      </Head>
      <Script src="transparent.js" strategy="lazyOnload" />
      <nav>
        <div className={navStyles.nav_title}>
          <Link href="/" className={navStyles.nav_title}>
            <a onClick={handleClick}>bone hollow</a>
          </Link>
        </div>
      </nav>
    </>
  );
}
