import Head from "next/head";
import Script from "next/script";
import Link from "next/link";
import navStyles from "../styles/navbar.module.css";

export default function NavBar() {
  return (
    <>
      <Head>
        <title>bone hollow studio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/leaf.svg"
          className="invert(68%) sepia(9%) saturate(467%) hue-rotate(64deg) brightness(93%) contrast(89%)"
        ></link>
      </Head>
      <Script src="transparent.js" strategy="lazyOnload" />
      <nav>
        <div className={navStyles.nav_about}>
          <Link href="/about">
            <a>about</a>
          </Link>
        </div>
        <div className={navStyles.nav_homes}>
          <Link href="/homes">
            <a>homes</a>
          </Link>
        </div>
        <div className={navStyles.nav_title}>
          <Link href="/" className={navStyles.nav_title}>
            <a>bone hollow</a>
          </Link>
        </div>
        <div className={navStyles.nav_hudson_valley}>
          <Link href="/hudsonValley">
            <a>hudson valley</a>
          </Link>
        </div>
        <div className={navStyles.nav_contact}>
          <Link href="/contact">
            <a>contact</a>
          </Link>
        </div>
      </nav>
    </>
  );
}
