import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import { useRouter } from "next/router";
import { handleSyntaxError } from "../src/utils";
import navStyles from "../styles/navbar.module.css";

export default function NavBar() {
  const handleClick = () => {
    document.body.classList.add("transparent-nav");
  };

  const router = useRouter();
  return (
    <>
      <Head>
        <title>bone hollow studio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/leaf.svg"
          className="invert(68%) sepia(9%) saturate(467%) hue-rotate(64deg) brightness(93%) contrast(89%)"
        ></link>
      </Head>
      {/* <Script
        src="transparent.js"
        strategy="lazyOnload"
        onError={handleSyntaxError}
      /> */}
      <nav>
        <div className={navStyles.nav_about}>
          <Link href="/about">
            <a
              onClick={handleClick}
              className={router.pathname == "/about" ? "active" : ""}
            >
              about
            </a>
          </Link>
        </div>
        <div className={navStyles.nav_homes}>
          <Link href="/homes">
            <a
              onClick={handleClick}
              className={router.pathname.includes("/homes") ? "active" : ""}
            >
              homes
            </a>
          </Link>
        </div>
        <div className={navStyles.nav_title}>
          <Link href="/" className={navStyles.nav_title}>
            <a
              onClick={handleClick}
              className={router.pathname == "/" ? "active" : ""}
            >
              bone hollow studio
            </a>
          </Link>
        </div>
        <div className={navStyles.nav_hudson_valley}>
          <Link href="/hudsonValley">
            <a
              onClick={handleClick}
              className={router.pathname == "/hudsonValley" ? "active" : ""}
            >
              hudson valley
            </a>
          </Link>
        </div>
        <div className={navStyles.nav_contact}>
          <Link href="/contact">
            <a
              onClick={handleClick}
              className={router.pathname == "/contact" ? "active" : ""}
            >
              contact
            </a>
          </Link>
        </div>
      </nav>
    </>
  );
}
